[package]
name = "core"
version = "0.1.0"
authors = ["Tim Harding <Tim@TimHarding.co>"]
edition = "2018"

[dependencies]
ropey = "1.2"
syntect = { version = "4.5", default-features = false, features = ["default-fancy"]}
anyhow = "1.0"
thiserror = "1.0"
